Repository Team-2m4t/Hyangyu-server, pull requests merged in 2022-01, with the labels that each got.

#2 [chore] mysql 의존성 추가
  build.gradle
Labels: kiyeon

#4 [feat]유저 도메인 추가(#3)
  src/main/java/hyangyu/server/domain/User.java
Labels: enhancement, Jinhee

#6 [fix]유저 도메인 변수 수정(#5)
  src/main/java/hyangyu/server/domain/User.java
Labels: bug, Jinhee

#10 [Fix] User.java 도메인 수정(#9)
  src/main/java/hyangyu/server/domain/User.java
Labels: bug, Jinhee

#18 [docs] .gitignore에 .DS_Store 추가 (#17)
  .gitignore
Labels: documentation, kiyeon

#20 [feat]유저Dto및유저Repository추가(#19)
  build.gradle
  src/main/java/hyangyu/server/api/UserController.java
  src/main/java/hyangyu/server/dto/StatusEnum.java
  src/main/java/hyangyu/server/dto/UserRequestDto.java
  src/main/java/hyangyu/server/dto/UserResponseDto.java
  src/main/java/hyangyu/server/repository/UserRepository.java
Labels: enhancement, Jinhee

#21 [feat] 리뷰 테이블 생성 (#11)
  build.gradle
  src/main/java/hyangyu/server/domain/DisplayReview.java
  src/main/java/hyangyu/server/domain/FairReview.java
  src/main/java/hyangyu/server/domain/FestivalReview.java
Labels: enhancement, yujin

#25 [feat]jwt 로그인/회원가입 구현(#23)
  .gitmessage.txt
  build.gradle
  src/main/java/hyangyu/server/api/AuthController.java
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/api/UserController.java
  src/main/java/hyangyu/server/api/dummyApi.java
  src/main/java/hyangyu/server/config/CorsConfig.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/Authority.java
  src/main/java/hyangyu/server/domain/User.java
  src/main/java/hyangyu/server/dto/AuthorityDto.java
  src/main/java/hyangyu/server/dto/ErrorDto.java
  src/main/java/hyangyu/server/dto/LoginDto.java
  src/main/java/hyangyu/server/dto/StatusEnum.java
  src/main/java/hyangyu/server/dto/TokenDto.java
  src/main/java/hyangyu/server/dto/UserDto.java
  src/main/java/hyangyu/server/dto/UserRequestDto.java
  src/main/java/hyangyu/server/dto/UserResponseDto.java
  src/main/java/hyangyu/server/jwt/DuplicateMemberException.java
  src/main/java/hyangyu/server/jwt/JwtAccessDeniedHandler.java
  src/main/java/hyangyu/server/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/hyangyu/server/jwt/JwtFilter.java
  src/main/java/hyangyu/server/jwt/JwtSecurityConfig.java
  src/main/java/hyangyu/server/jwt/MethodArgumentNotValidExceptionHandler.java
  src/main/java/hyangyu/server/jwt/RestResponseEntityExceptionHandler.java
  src/main/java/hyangyu/server/jwt/SecurityUtil.java
  src/main/java/hyangyu/server/jwt/TokenProvider.java
  src/main/java/hyangyu/server/repository/AuthorityRepository.java
  src/main/java/hyangyu/server/repository/UserRepository.java
  src/main/java/hyangyu/server/repository/dummyRepository.java
  src/main/java/hyangyu/server/service/CustomUserDetailsService.java
  src/main/java/hyangyu/server/service/UserService.java
  src/main/java/hyangyu/server/service/dummyService.java
Labels: enhancement, Jinhee

#27 [fix]유저 도메인 수정(#26)
  src/main/java/hyangyu/server/domain/User.java
  src/main/java/hyangyu/server/dto/UserDto.java
  src/main/java/hyangyu/server/service/UserService.java
Labels: bug, Jinhee

#30 [feat] 내가 저장한 전시회 api
  build.gradle
  src/main/java/hyangyu/server/api/FavoriteApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/Display.java
  src/main/java/hyangyu/server/domain/Fair.java
  src/main/java/hyangyu/server/domain/FavoriteDisplay.java
  src/main/java/hyangyu/server/domain/FavoriteDisplayId.java
  src/main/java/hyangyu/server/domain/Festival.java
  src/main/java/hyangyu/server/domain/User.java
  src/main/java/hyangyu/server/dto/EventDto.java
  src/main/java/hyangyu/server/dto/SaveFavoriteResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayRepository.java
  src/main/java/hyangyu/server/repository/FavoriteDisplayRepository.java
  src/main/java/hyangyu/server/repository/UserRepository.java
  src/main/java/hyangyu/server/service/DisplayService.java
  src/main/java/hyangyu/server/service/FavoriteDisplayService.java
  src/main/java/hyangyu/server/service/UserService.java
  src/test/java/hyangyu/server/repository/FavoriteDisplayRepositoryTest.java
Labels: enhancement, kiyeon

#33 전시회 리뷰 작성 api
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/DisplayReview.java
  src/main/java/hyangyu/server/domain/FairReview.java
  src/main/java/hyangyu/server/domain/FestivalReview.java
  src/main/java/hyangyu/server/dto/RequestReviewDto.java
  src/main/java/hyangyu/server/dto/SaveReviewResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/repository/FestivalReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: enhancement, yujin

#35 [feat] 내가 저장한 박람회, 페스티벌 저장 API
  src/main/java/hyangyu/server/api/FavoriteApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/Fair.java
  src/main/java/hyangyu/server/domain/FavoriteFair.java
  src/main/java/hyangyu/server/domain/FavoriteFairId.java
  src/main/java/hyangyu/server/domain/FavoriteFestival.java
  src/main/java/hyangyu/server/domain/FavoriteFestivalId.java
  src/main/java/hyangyu/server/domain/Festival.java
  src/main/java/hyangyu/server/repository/FairRepository.java
  src/main/java/hyangyu/server/repository/FavoriteFairRepository.java
  src/main/java/hyangyu/server/repository/FavoriteFestivalRepository.java
  src/main/java/hyangyu/server/repository/FestivalRepository.java
  src/main/java/hyangyu/server/service/FairService.java
  src/main/java/hyangyu/server/service/FavoriteDisplayService.java
  src/main/java/hyangyu/server/service/FavoriteFairService.java
  src/main/java/hyangyu/server/service/FavoriteFestivalService.java
  src/main/java/hyangyu/server/service/FestivalService.java
  src/test/java/hyangyu/server/repository/FavoriteFairRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFestivalRepositoryTest.java
Labels: enhancement, kiyeon

#39 [도메인] 전시/박람회/페스티벌 holiday 필드값 변경
  src/main/java/hyangyu/server/api/FavoriteApi.java
  src/main/java/hyangyu/server/domain/Display.java
  src/main/java/hyangyu/server/domain/Fair.java
  src/main/java/hyangyu/server/domain/Festival.java
  src/main/java/hyangyu/server/dto/EventDto.java
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FavoriteDisplayRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFairRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFestivalRepositoryTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: enhancement, kiyeon

#41 [feat] 박람회, 페스티벌 리뷰 저장 api
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
Labels: enhancement, yujin

#44 [feat]유저 닉네임 변경/비밀번호 변경 기능 추가(#43)
  src/main/java/hyangyu/server/api/AuthController.java
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/domain/User.java
  src/main/java/hyangyu/server/service/UserService.java
Labels: enhancement, Jinhee
