Repository Team-2m4t/Hyangyu-server, pull requests merged in 2022-02, with the labels that each got.

#48 [이벤트] 내가 저장한 전시/박람회/페스티벌 삭제 API
  src/main/java/hyangyu/server/api/FavoriteApi.java
  src/main/java/hyangyu/server/domain/DisplayReview.java
  src/main/java/hyangyu/server/domain/FairReview.java
  src/main/java/hyangyu/server/domain/FavoriteDisplay.java
  src/main/java/hyangyu/server/domain/FavoriteFair.java
  src/main/java/hyangyu/server/domain/FavoriteFestival.java
  src/main/java/hyangyu/server/domain/FestivalReview.java
  src/main/java/hyangyu/server/dto/ResponseDto.java
  src/main/java/hyangyu/server/repository/FavoriteDisplayRepository.java
  src/main/java/hyangyu/server/repository/FavoriteFairRepository.java
  src/main/java/hyangyu/server/repository/FavoriteFestivalRepository.java
  src/main/java/hyangyu/server/service/FavoriteDisplayService.java
  src/main/java/hyangyu/server/service/FavoriteFairService.java
  src/main/java/hyangyu/server/service/FavoriteFestivalService.java
Labels: enhancement, kiyeon

#49 [feat] 전시, 박람회, 페스티벌 리뷰 삭제 api
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: enhancement, yujin

#52 [feat]UserDto userId 추가(#51)
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/dto/ModificationDto.java
  src/main/java/hyangyu/server/dto/UserDto.java
Labels: enhancement, Jinhee

#54 [feat]회원탈퇴(#53)
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/service/UserService.java
Labels: enhancement, Jinhee

#56 [feat] jwt 해독하고 사용자 찾는 코드 추가
  src/main/java/hyangyu/server/api/FavoriteApi.java
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/service/UserService.java
Labels: enhancement, kiyeon

#60 [feat]유저 블락 기능 추가(#59)
  src/main/java/hyangyu/server/api/BlockApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/BlockedUser.java
  src/main/java/hyangyu/server/domain/BlockedUserId.java
  src/main/java/hyangyu/server/repository/BlockedUserRepository.java
  src/main/java/hyangyu/server/service/BlockService.java
Labels: enhancement, Jinhee

#63 [fix] 리뷰 저장 api 수정
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/domain/DisplayReview.java
  src/main/java/hyangyu/server/domain/FairReview.java
  src/main/java/hyangyu/server/domain/FestivalReview.java
  src/main/java/hyangyu/server/dto/SaveReviewResponseDto.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: bug, yujin

#62 [feat] 마이페이지 조회 API (#36)
  build.gradle
  src/main/java/hyangyu/server/api/FavoriteApi.java
  src/main/java/hyangyu/server/api/MyPageApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/Display.java
  src/main/java/hyangyu/server/domain/Fair.java
  src/main/java/hyangyu/server/domain/Festival.java
  src/main/java/hyangyu/server/dto/EventDto.java
  src/main/java/hyangyu/server/dto/ReviewDto.java
  src/main/java/hyangyu/server/dto/TestEventDto.java
  src/main/java/hyangyu/server/dto/myPage/MyPageDto.java
  src/main/java/hyangyu/server/dto/myPage/MyPageResponseDto.java
  src/main/java/hyangyu/server/repository/FavoriteFairRepository.java
  src/main/java/hyangyu/server/repository/FavoriteFestivalRepository.java
  src/main/java/hyangyu/server/repository/MyPageRepository.java
  src/main/java/hyangyu/server/service/DisplayService.java
  src/main/java/hyangyu/server/service/FairService.java
  src/main/java/hyangyu/server/service/FavoriteFestivalService.java
  src/main/java/hyangyu/server/service/FestivalService.java
  src/main/java/hyangyu/server/service/MyPageService.java
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FavoriteDisplayRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFairRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFestivalRepositoryTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: enhancement, kiyeon

#67 [feat] 리뷰 신고 API
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/DisplayReview.java
  src/main/java/hyangyu/server/domain/DisplayWarn.java
  src/main/java/hyangyu/server/domain/FairReview.java
  src/main/java/hyangyu/server/domain/FairWarn.java
  src/main/java/hyangyu/server/domain/FestivalReview.java
  src/main/java/hyangyu/server/domain/FestivalWarn.java
  src/main/java/hyangyu/server/repository/DisplayWarnRepository.java
  src/main/java/hyangyu/server/repository/FairWarnRepository.java
  src/main/java/hyangyu/server/repository/FestivalWarnRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
Labels: enhancement, yujin

#70 [fix]json 리턴되도록 수정하기(#69)
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/service/UserService.java
Labels: bug, Jinhee

#71 [카테고리] 카테고리 API
  src/main/java/hyangyu/server/api/CategoryApi.java
  src/main/java/hyangyu/server/api/MyPageApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/dto/event/DisplayDto.java
  src/main/java/hyangyu/server/dto/event/DisplayResponseDto.java
  src/main/java/hyangyu/server/dto/event/FairDto.java
  src/main/java/hyangyu/server/dto/event/FairResponseDto.java
  src/main/java/hyangyu/server/dto/event/FestivalDto.java
  src/main/java/hyangyu/server/dto/event/FestivalResponseDto.java
  src/main/java/hyangyu/server/dto/event/MyPageDto.java
  src/main/java/hyangyu/server/dto/event/MyPageResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayRepository.java
  src/main/java/hyangyu/server/repository/MyPageRepository.java
  src/main/java/hyangyu/server/service/MyPageService.java
Labels: enhancement, kiyeon

#72 [feat] 전시 리뷰 조회 API
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/dto/ReviewDto.java
  src/main/java/hyangyu/server/dto/ReviewsResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
Labels: enhancement, yujin

#74 [fix] 리뷰 테이블 nickname 삭제
  src/main/java/hyangyu/server/domain/DisplayReview.java
  src/main/java/hyangyu/server/domain/FairReview.java
  src/main/java/hyangyu/server/domain/FestivalReview.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: bug, yujin

#76 [feat] 내가 쓴 리뷰 조회 API
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/dto/MyReviewsDto.java
  src/main/java/hyangyu/server/dto/MyReviewsResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/repository/FestivalReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
Labels: enhancement, yujin

#82 [feat] 전시, 박람회, 페스티벌 검색 API
  src/main/java/hyangyu/server/api/SearchApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/dto/event/SearchDto.java
  src/main/java/hyangyu/server/dto/event/SearchResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayRepository.java
  src/main/java/hyangyu/server/repository/FairRepository.java
  src/main/java/hyangyu/server/repository/FestivalRepository.java
  src/main/java/hyangyu/server/service/SearchService.java
Labels: enhancement, yujin

#83 [fix] 리뷰 저장, 조회 API 수정
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/dto/ReviewDto.java
  src/main/java/hyangyu/server/dto/SaveReviewResponseDto.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/repository/FestivalReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
Labels: bug, yujin

#85 [fix] 전시 리뷰 조회 API 수정
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/dto/review/MyReviewsDto.java
  src/main/java/hyangyu/server/dto/review/MyReviewsResponseDto.java
  src/main/java/hyangyu/server/dto/review/RequestReviewDto.java
  src/main/java/hyangyu/server/dto/review/ReviewDto.java
  src/main/java/hyangyu/server/dto/review/ReviewsResponseDto.java
  src/main/java/hyangyu/server/dto/review/SaveReviewResponseDto.java
  src/main/java/hyangyu/server/dto/review/ShowReviewsDto.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/repository/FestivalReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
Labels: bug, yujin

#89 [fix] 내가 쓴 리뷰 조회 api 변경
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/dto/review/MyReviewDto.java
  src/main/java/hyangyu/server/dto/review/MyReviewsDto.java
  src/main/java/hyangyu/server/repository/DisplayReviewRepository.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/repository/FestivalReviewRepository.java
  src/main/java/hyangyu/server/service/DisplayReviewService.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
Labels: bug, yujin

#91 [feat]유저 관련 api 도메인 주소 수정(#88)
  .gitignore
  build.gradle
  src/main/java/hyangyu/server/api/AuthApi.java
  src/main/java/hyangyu/server/api/BlockApi.java
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
Labels: enhancement, Jinhee
