Repository Team-2m4t/Hyangyu-server, pull requests merged in 2022-03, with the labels that each got.

#97 [feat] smtp 비밀번호 찾기 구현하기(#96)
  .gitignore
  build.gradle
  src/main/java/hyangyu/server/api/AuthApi.java
  src/main/java/hyangyu/server/api/AuthNumApi.java
  src/main/java/hyangyu/server/api/EmailApi.java
  src/main/java/hyangyu/server/api/UserApi.java
  src/main/java/hyangyu/server/config/SecurityConfig.java
  src/main/java/hyangyu/server/domain/AuthNum.java
  src/main/java/hyangyu/server/dto/EmailDto.java
  src/main/java/hyangyu/server/repository/AuthNumRepository.java
  src/main/java/hyangyu/server/service/AuthNumService.java
  src/main/java/hyangyu/server/service/EmailService.java
Labels: enhancement, Jinhee

#99 [feat] 박람회, 페스티벌 리뷰 조회 API
  src/main/java/hyangyu/server/api/ReviewApi.java
  src/main/java/hyangyu/server/repository/FairReviewRepository.java
  src/main/java/hyangyu/server/repository/FestivalReviewRepository.java
  src/main/java/hyangyu/server/service/FairReviewService.java
  src/main/java/hyangyu/server/service/FestivalReviewService.java
Labels: enhancement, yujin

#101 [fix] 테스트코드 eventDto import 수정
  src/test/java/hyangyu/server/repository/DisplayReviewTest.java
  src/test/java/hyangyu/server/repository/FairReviewTest.java
  src/test/java/hyangyu/server/repository/FavoriteDisplayRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFairRepositoryTest.java
  src/test/java/hyangyu/server/repository/FavoriteFestivalRepositoryTest.java
  src/test/java/hyangyu/server/repository/FestivalReviewTest.java
Labels: bug, yujin
